export const columns = [
  {
    title: '名称',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '人数',
    dataIndex: 'number',
    key: 'number',
  },
];

export const tableData = [
  {
    parentId: 0,
    id: 1,
    name: '分组1',
    number: '10',
    type: 'group',
    key: '0',
    // level: 1,
    children: [
      {
        parentId: 1,
        id: 2,
        name: '分组1-测试1',
        number: '2',
        type: 'child',
        key: '0-0',
        // level: 2,
      },
      {
        parentId: 1,
        id: 3,
        name: '分组1-测试2',
        number: '5',
        type: 'child',
        key: '0-1',
        // level: 2,
      },
      {
        parentId: 1,
        id: 4,
        name: '分组1-测试3',
        number: '3',
        type: 'child',
        key: '0-2',
        // level: 2,
      },
    ],
  },
  {
    parentId: 0,
    id: 5,
    name: '分组2',
    number: '3',
    type: 'group',
    key: '1',
    // level: 1,
    children: [
      {
        parentId: 5,
        id: 6,
        name: '分组2-测试1',
        number: '2',
        type: 'child',
        key: '1-0',
        // level: 2,
      },
      {
        parentId: 5,
        id: 7,
        name: '分组2-测试2',
        number: '1',
        type: 'child',
        key: '1-1',
        // level: 2,
      },
    ],
  },
  {
    parentId: 0,
    id: 8,
    name: '测试child-1',
    number: '3',
    type: 'child',
    key: '2',
    // level: 1,
  },
  {
    parentId: 0,
    id: 9,
    name: '测试child-2',
    number: '2',
    type: 'child',
    key: '3',
    // level: 1,
  },
];
